- import_playbook: 01-setup-load-balancer.yaml
- import_playbook: 02-prepare-k8s-nodes.yaml
- import_playbook: 03-initialize-k8s-cluster.yaml
- import_playbook: 04-install-cni.yaml
- import_playbook: 05-add-additional-master-nodes.yaml
- import_playbook: 06-add-worker-nodes.yaml
- import_playbook: 07-install-ingress-controller.yaml
- import_playbook: 07-install-metrics-server.yaml
- import_playbook: 08-install-vpa.yaml
